export enum GameErrorCode {
  // Auth (1xx)
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_NAME = 'AUTH_INVALID_NAME',
  AUTH_RATE_LIMITED = 'AUTH_RATE_LIMITED',

  // Lobby (2xx)
  LOBBY_GAME_NOT_FOUND = 'LOBBY_GAME_NOT_FOUND',
  LOBBY_GAME_FULL = 'LOBBY_GAME_FULL',
  LOBBY_GAME_STARTED = 'LOBBY_GAME_STARTED',
  LOBBY_ALREADY_JOINED = 'LOBBY_ALREADY_JOINED',
  LOBBY_NOT_JOINED = 'LOBBY_NOT_JOINED',
  LOBBY_NOT_CREATOR = 'LOBBY_NOT_CREATOR',
  LOBBY_INVALID_CONFIG = 'LOBBY_INVALID_CONFIG',
  LOBBY_INVALID_PASSWORD = 'LOBBY_INVALID_PASSWORD',
  LOBBY_MIN_PLAYERS = 'LOBBY_MIN_PLAYERS',

  // Game Actions (3xx)
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_NOT_STARTED = 'GAME_NOT_STARTED',
  GAME_ALREADY_OVER = 'GAME_ALREADY_OVER',
  GAME_NOT_YOUR_TURN = 'GAME_NOT_YOUR_TURN',
  GAME_INVALID_TERRITORY = 'GAME_INVALID_TERRITORY',
  GAME_TERRITORY_NOT_OWNED = 'GAME_TERRITORY_NOT_OWNED',
  GAME_TERRITORY_NOT_ADJACENT = 'GAME_TERRITORY_NOT_ADJACENT',
  GAME_TERRITORY_OWN = 'GAME_TERRITORY_OWN',
  GAME_INSUFFICIENT_DICE = 'GAME_INSUFFICIENT_DICE',
  GAME_ALLIED_TERRITORY = 'GAME_ALLIED_TERRITORY',

  // Power-ups (4xx)
  GAME_POWERUP_NOT_FOUND = 'GAME_POWERUP_NOT_FOUND',
  GAME_POWERUP_INVALID_TARGET = 'GAME_POWERUP_INVALID_TARGET',
  GAME_POWERUP_INVALID_SOURCE = 'GAME_POWERUP_INVALID_SOURCE',

  // Undo (5xx)
  GAME_UNDO_DISABLED = 'GAME_UNDO_DISABLED',
  GAME_UNDO_NO_SNAPSHOT = 'GAME_UNDO_NO_SNAPSHOT',

  // Alliance (6xx)
  GAME_ALLIANCE_DISABLED = 'GAME_ALLIANCE_DISABLED',
  GAME_ALLIANCE_INVALID_TARGET = 'GAME_ALLIANCE_INVALID_TARGET',
  GAME_ALLIANCE_ALREADY_ALLIED = 'GAME_ALLIANCE_ALREADY_ALLIED',
  GAME_ALLIANCE_PROPOSAL_NOT_FOUND = 'GAME_ALLIANCE_PROPOSAL_NOT_FOUND',

  // Spectator (75x)
  SPECTATOR_CANNOT_ACT = 'SPECTATOR_CANNOT_ACT',

  // Connection (7xx)
  CONNECTION_GAME_ENDED = 'CONNECTION_GAME_ENDED',
  CONNECTION_NOT_IN_GAME = 'CONNECTION_NOT_IN_GAME',

  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
}

export interface GameError {
  code: GameErrorCode;
  message: string;
  details?: Record<string, unknown>;
}

export const ERROR_HTTP_STATUS: Record<GameErrorCode, number> = {
  // Auth
  [GameErrorCode.AUTH_REQUIRED]: 401,
  [GameErrorCode.AUTH_INVALID_TOKEN]: 401,
  [GameErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [GameErrorCode.AUTH_INVALID_NAME]: 400,
  [GameErrorCode.AUTH_RATE_LIMITED]: 429,

  // Lobby
  [GameErrorCode.LOBBY_GAME_NOT_FOUND]: 404,
  [GameErrorCode.LOBBY_GAME_FULL]: 409,
  [GameErrorCode.LOBBY_GAME_STARTED]: 409,
  [GameErrorCode.LOBBY_ALREADY_JOINED]: 409,
  [GameErrorCode.LOBBY_NOT_JOINED]: 400,
  [GameErrorCode.LOBBY_NOT_CREATOR]: 403,
  [GameErrorCode.LOBBY_INVALID_CONFIG]: 400,
  [GameErrorCode.LOBBY_INVALID_PASSWORD]: 403,
  [GameErrorCode.LOBBY_MIN_PLAYERS]: 400,

  // Game Actions
  [GameErrorCode.GAME_NOT_FOUND]: 404,
  [GameErrorCode.GAME_NOT_STARTED]: 400,
  [GameErrorCode.GAME_ALREADY_OVER]: 409,
  [GameErrorCode.GAME_NOT_YOUR_TURN]: 403,
  [GameErrorCode.GAME_INVALID_TERRITORY]: 400,
  [GameErrorCode.GAME_TERRITORY_NOT_OWNED]: 403,
  [GameErrorCode.GAME_TERRITORY_NOT_ADJACENT]: 400,
  [GameErrorCode.GAME_TERRITORY_OWN]: 400,
  [GameErrorCode.GAME_INSUFFICIENT_DICE]: 400,
  [GameErrorCode.GAME_ALLIED_TERRITORY]: 400,

  // Power-ups
  [GameErrorCode.GAME_POWERUP_NOT_FOUND]: 404,
  [GameErrorCode.GAME_POWERUP_INVALID_TARGET]: 400,
  [GameErrorCode.GAME_POWERUP_INVALID_SOURCE]: 400,

  // Undo
  [GameErrorCode.GAME_UNDO_DISABLED]: 403,
  [GameErrorCode.GAME_UNDO_NO_SNAPSHOT]: 400,

  // Alliance
  [GameErrorCode.GAME_ALLIANCE_DISABLED]: 403,
  [GameErrorCode.GAME_ALLIANCE_INVALID_TARGET]: 400,
  [GameErrorCode.GAME_ALLIANCE_ALREADY_ALLIED]: 409,
  [GameErrorCode.GAME_ALLIANCE_PROPOSAL_NOT_FOUND]: 404,

  // Spectator
  [GameErrorCode.SPECTATOR_CANNOT_ACT]: 403,

  // Connection
  [GameErrorCode.CONNECTION_GAME_ENDED]: 410,
  [GameErrorCode.CONNECTION_NOT_IN_GAME]: 400,

  // Generic
  [GameErrorCode.INTERNAL_ERROR]: 500,
  [GameErrorCode.RATE_LIMITED]: 429,
};
